### ISSUE TITLE
Extension not showing icon by the clock. Ubuntu 20.04 with gnome shell installed. Thank you. 

### ISSUE THREAD

**Issue by fernando-design** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#11] opened 2020-06-01 20:45 UTC

**Comment by JasonLG1979** [comment] 2020-06-03 03:16
Duplicate of https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/issues/10

**Closed by JasonLG1979** 2020-06-03 03:16 UTC
