### ISSUE TITLE
Font Issue?

### ISSUE THREAD

**Issue by jjvcuyler** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#17] opened 2021-06-18 05:02 UTC
## Distro Name & Version
Gentoo Base System release 2.7

## GNOME Shell Version
40.2

## Other Installed Extensions
ArcMenu
Auto Move Windows
Compiz alike magic lamp effect
Compiz windows effect
Espresso
Frippery Panel Favorites
Home Assistant Extension
Launch new instance
Native Window Placement
Places Status Indicator
Removable Drive Menu
Screen Autorotate
Screenshot Window Sizer
User Themes
Window List
windowNavigator
Workspace Indicator

## Expected Behavior
The temperature should be displayed as a number followed by °F or °C

## Current Behavior
The temperature is displayed as a number followed by a solid square

## Detailed Description
There's not much more to add. I suspect it's a font issue, but that wouldn't explain why the F or C is not showing. It's the same issue described by octob0t on the Gnome Extensions page. Here's a screenshot (octob0t's, not mine) [https://imgur.com/a/5gWsOb3](url)

**Comment by JasonLG1979** [comment] 2021-06-25 15:20
Duplicate of https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/issues/18 or rather that issue is a duplicate of this one. In any case see that issue for details.

**Closed by JasonLG1979** 2021-06-25 15:20 UTC
